### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by zenprocess**

### CODE REVIEW

**Comment by elboletaire** [comment]
What? xD

**Comment by zenprocess** [comment]
lol, trying to make this actually work

**Comment by elboletaire** [comment]
Oh, I think @gtrias (the one who created that template) never got huginn working. Or did you, @gtrias?

**Comment by gtrias** [comment]
I have it working in my rancher. But maybe i did a manual step the day I was building the stack.

Can you tell me what errors you get @zenprocess ?

**Comment by zenprocess** [comment]
few things:

1) the mysql container is incorrectly linked
2) there is no DATABASE_HOST environment var specified so added that
3) in the huginn containers if I look at database.yml does not seem to pick up the database password from vars so ends up trying to logon with username root and password password

**Comment by gtrias** [comment]
My exported configuration is the next:

docker-compose.yml
```yaml
version: '2'
services:
  huginn-threaded:
    image: cantino/huginn-single-process
    environment:
      APP_SECRET_TOKEN: xxxxxxxxxx
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn
      DATABASE_PASSWORD: xxxxxxxxx
      DATABASE_USERNAME: root
      RAILS_ENV: production
      SMTP_USER_NAME: xxxxx@xxxxxx
      SMTP_PASSWORD: 'xxxxxxxxx'
      SMTP_SERVER: mail.xxx.xx
      SMTP_PORT: '25'
      SMTP_AUTHENTICATION: plain
      SMTP_ENABLE_STARTTLS_AUTO: 'true'
      EMAIL_FROM_ADDRESS: xxxxx@xxxxxx
      SMTP_DOMAIN: xxxxxx
    links:
    - mysql:mysql
    command:
    - /scripts/init
    - bin/threaded.rb
    labels:
      io.rancher.container.pull_image: always
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxx
    entrypoint:
    - /entrypoint.sh
    volumes:
    - /rpool/docker-storage/huginn/mysql:/var/lib/mysql
    tty: true
    command:
    - mysqld
    labels:
      io.rancher.container.pull_image: always
  huginn-web:
    image: cantino/huginn-single-process
    environment:
      APP_SECRET_TOKEN: xxxxxxx
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn
      DATABASE_PASSWORD: xxxxxxxxx
      DATABASE_USERNAME: root
      RAILS_ENV: production
      SMTP_USER_NAME: xxxxx@xxxxxx
      SMTP_PASSWORD: 'xxxxxxxxx'
      SMTP_SERVER: mail.xxx.xx
      SMTP_PORT: '25'
      SMTP_AUTHENTICATION: plain
      SMTP_ENABLE_STARTTLS_AUTO: 'true'
      EMAIL_FROM_ADDRESS: xxxxx@xxxxxx
      SMTP_DOMAIN: xxxxxx
      VIRTUAL_HOST: xxxxxxxxxxxxxxxxxxxx
    external_links:
    - mysql/mysql:mysql
    ports:
    - 5000/tcp
    labels:
      io.rancher.container.pull_image: always
```

rancher-compose.yml
```yaml

version: '2'
services:
  huginn-threaded:
    scale: 1
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true
  huginn-web:
    scale: 1
    start_on_create: true
```
Maybe it could help

**Pull request closed without merging**
